name: Publish

on:
    push:
        tags:
            - "v*"

jobs:
    publish:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - name: Install llvm and clang
              run: sudo apt-get install llvm clang
            - name: Install CMake
              run: sudo apt-get install cmake
            - name: Install Ninja
              run: sudo apt-get install ninja-build
            - name: Install Emscripten
              uses: mymindstorm/setup-emsdk@v12
              with:
                  version: 3.1.46

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"
                  registry-url: "https://registry.npmjs.org"

            - name: Install wasm-opt
              run: |
                  npm install -g binaryen

            - name: Build
              run: ./scripts/build.sh
              shell: bash
              env:
                  WASM_OPT: 1

            - name: Publish to npm
              run: cd npm && npm publish --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"
                  registry-url: "https://npm.pkg.github.com"

            - name: Publish to GitHub Packages
              run: cd npm && npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Pack
              run: cd npm && npm pack

            - name: Publish to Github Releases
              uses: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d
              with:
                  files: |
                      npm/*.tgz
