name: Publish

on:
    create:
        tags:
            - "v*"

jobs:
    publish:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: write
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
            - name: Install llvm and clang
              run: sudo apt-get install llvm clang
            - name: Install CMake
              run: sudo apt-get install cmake
            - name: Install Ninja
              run: sudo apt-get install ninja-build
            - name: Install Emscripten
              uses: mymindstorm/setup-emsdk@v11
              with:
                  version: 3.1.44

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"
                  registry-url: "https://registry.npmjs.org"

            - name: Build
              run: ./scripts/build.sh

            - name: Publish to npm
              run: (cd npm && npm publish)
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"
                  registry-url: "https://npm.pkg.github.com"

            - name: Publish to GitHub Packages
              run: (cd npm && npm publish)
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Pack
              run: (cd npm && npm pack)

            - name: Publish to Github Releases
              uses: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d
              with:
                  files: |
                      npm/*.tgz
